/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepublicDataRouteImport } from './routes/republic-data'
import { Route as IndexRouteImport } from './routes/index'

const RepublicDataRoute = RepublicDataRouteImport.update({
  id: '/republic-data',
  path: '/republic-data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/republic-data': typeof RepublicDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/republic-data': typeof RepublicDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/republic-data': typeof RepublicDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/republic-data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/republic-data'
  id: '__root__' | '/' | '/republic-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepublicDataRoute: typeof RepublicDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/republic-data': {
      id: '/republic-data'
      path: '/republic-data'
      fullPath: '/republic-data'
      preLoaderRoute: typeof RepublicDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepublicDataRoute: RepublicDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
